services:
  # 1. The Database
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      # सोर्स (वॉल्यूम नाम) : डेस्टिनेशन (कंटेनर के अंदर का पाथ)
      - postgres_data:/var/lib/postgresql/data
    networks:
      - Excalidraw

  website:
    build:
      context: .
      dockerfile: ./Docker/docker-http.dockerfile
    container_name: http-server
    ports:
      - "3000:3000"
      - "3002:3002"
      - "8080:8080"
    depends_on:
      - db
    networks:
      - Excalidraw

networks:
  Excalidraw:
    driver: bridge

volumes:
  postgres_data:
